export const FETCH_PATIENT_CASES = 'FETCH_PATIENT_CASES';
export const FETCH_PATIENT_CASE = 'FETCH_PATIENT_CASE';
export const SET_PATIENT_CASE_FILTERS = 'SET_PATIENT_CASE_FILTERS';
export const APPEND_PATIENT_CASE = 'APPEND_PATIENT_CASE';
export const APPEND_PATIENT_CASES = 'APPEND_PATIENT_CASES';
